### PR TITLE
Example with onnx

### PR DESCRIPTION
**Pull request by hhsecond**
Addressing #124

### CODE REVIEW

**Comment by lantiga** [comment]
On second though, this probably belongs to the `examples` repo. What do you think?

**Comment by hhsecond** [comment]
That's what my instinct was too. But  then we have at least one example for each backend in this repo. If we are planning to remove all the examples from here, it make sense to move it there.

**Comment by lantiga** [comment]
I agree, the examples folder needs to be cleaned up. However, some of it can go in `redisai-examples`, some as tests. Let's use this opportunity to see what goes where.

**Comment by K-Jo** [comment]
I believe that both folder here and in ai-examples need a clean up.  However keeping this dangling here now we made a release feels poor.  I'll make a ticket to force us to clean this up

**Pull request merged**
