### PR TITLE
Add TAG to models and revamp MODELGET

### PR DESCRIPTION
**Pull request by lantiga**
Addresses:
* #306 by adding an optional `TAG <tag>` argument to `AI.MODELSET` and `AI.SCRIPTSET`; tags are returned by `AI.MODELGET` and `AI.SCRIPTGET` and they are reported as part of `AI.INFO`
* #304 by adding a `META` or `BLOB` argument to `AI.MODELGET` and `META` or `SOURCE` argument to `AI.SCRIPTGET` to get information like backend, device, tag, with or without the actual model blob or script source
* #303 by adding two new commands `AI.MODELLIST` and `AI.SCRIPTLIST`, that return key and tag for each model or script respectively

### CODE REVIEW

**Comment by lantiga** [comment]
@K-Jo @gkorland @filipecosta90 @hhsecond 
Since we're still unsure about the `MODELLIST` and `SCRIPTLIST` commands, can we still merge and mark them `experimental` or remove them from the API and merge the rest?

**Comment by hhsecond** [comment]
It'd help me to make the MLFlow integration easier if we have MODELLIST. I think we should keep it and mark it as experimental

**Comment by lantiga** [comment]
I agree with this, let's get moving. @hhsecond can you take a look at the PR?

**Comment by filipecosta90** [comment]
@lantiga and @hhsecond i believe that we should split this PR to exclude #303 . Lets approve #306 and #304 changes and discuss further the listing/scanning :)

**Comment by lantiga** [comment]
@filipecosta90 how long do you think it will take? I'd rather not have scan hold up MLFlow integration. We can always switch listing to scan at a later time.

**Comment by lantiga** [comment]
We could eventually avoid having those commands in the documentation, so that MLFlow integration can use them but they are not advertised. And maybe prepend them with `_`, like `AI._MODELLIST` to further reinforce the fact you shouldn't use them.

**Comment by filipecosta90** [comment]
>  prepend them with `_`, like `AI._MODELLIST` to further reinforce the fact you shouldn't use them.

agree :+1: :) 
Until we figure out the new API it's ok if he'll push forward with these experimental APIs

**Comment by hhsecond** [comment]
Awesome, thanks guys

**Pull request merged**
