### PR TITLE
Fix disconnection crash

### PR DESCRIPTION
**Pull request by lantiga**
Addresses #197

### CODE REVIEW

**Comment by filipecosta90** [comment]
@lantiga the previous flow in which I was able to replicate #197 ( run the aibench benchmark and force it to stop abruptly) now does not crashes redis-server.

**Comment by clslrns** [comment]
Hey, guys! I caught the same error on production, but with my own module. It happens rarely, like few times in a week in a high-loaded cluster of 12 nodes. 

Here is what I do:
```
RedisModuleBlockedClient *bc = RedisModule_BlockClient(ctx, NULL, NULL, NULL, 0);
// pthread_create, passing arguments, bla-bla
RedisModuleCtx *ctx = RedisModule_GetThreadSafeContext(bc);
```

The error is following:
```
=== REDIS BUG REPORT START: Cut & paste starting from here ===
27960:S 29 Oct 2019 13:09:37.546 # Redis 5.0.5 crashed by signal: 11
27960:S 29 Oct 2019 13:09:37.546 # Crashed running the instruction at: 0x55925339f0b6
27960:S 29 Oct 2019 13:09:37.546 # Accessing address: (nil)
27960:S 29 Oct 2019 13:09:37.546 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
EIP:
/usr/bin/redis-server 0.0.0.0:6379 [cluster](RM_GetThreadSafeContext+0xd6)[0x55925339f0b6]

Backtrace:
/usr/bin/redis-server 0.0.0.0:6379 [cluster](logStackTrace+0x41)[0x559253375741]
/usr/bin/redis-server 0.0.0.0:6379 [cluster](sigsegvHandler+0xc9)[0x559253375ec9]
/lib64/libpthread.so.0(+0xf5d0)[0x7fb9a3ecd5d0]
/usr/bin/redis-server 0.0.0.0:6379 [cluster](RM_GetThreadSafeContext+0xd6)[0x55925339f0b6]
/usr/lib64/redis/modules/zrevmerge.so(+0x38fa)[0x7fb99ad4e8fa]
```

I looked up Redis issues and there was one, but now closed: https://github.com/antirez/redis/issues/6355
How do you think, Is it really module-side issue or module API is the one to blame?
I doubt if simple null check will help here.

**Comment by clslrns** [comment]
@lantiga, what stops me from this is that I really dont use RedisAI : )
I tend to think it's kinda general Redis Modules API issue.

**Comment by lantiga** [comment]
Oh I see! Sorry, I didn't parse the whole sentence:
> Hey, guys! I caught the same error on production, **but with my own module**.

**Comment by antirez** [comment]
Pinging @lantiga about this: https://github.com/antirez/redis/issues/6525, it was likely a Redis core bug.

**Comment by lantiga** [comment]
Thank you @antirez, appreciated the fix and the ping 👍

**Pull request merged**
