### PR TITLE
Add getkeys-api to the DAGRUN command

### PR DESCRIPTION
**Pull request by lantiga**
Addresses #434

### CODE REVIEW

**Comment by gkorland** [comment]
@lantiga I don't see where you call `RedisModule_KeyAtPos` and `RedisModule_IsKeysPositionRequest`

**Comment by lantiga** [comment]
You are right, my bad.
After further consideration though, we will need to defer this to after merging #424: in the new DAGRUN PR we factor out parsing all kets before blocking, which makes it a lot easier to implement the missing functions.

**Comment by lantiga** [comment]
In scope: #160 #161

**Comment by filipecosta90** [comment]
closing this one in favor of #438 , which already addresses this issue for MODELRUN, DAGRUN, and SCRIPTRUN

**Pull request closed without merging**
