### PR TITLE
changed encver compare

### PR DESCRIPTION
**Pull request by DvirDukhan**

### CODE REVIEW

**Comment by lantiga** [comment]
This enables chunking if the version is `= 100`, although chunking is being backported in the context of #450. In other words, chunking wasn't there in RedisAI 1.0. What is the rationale for this change?

**Comment by DvirDukhan** [comment]
@lantiga 
`1.0.x` encver is 100
this means that backporting chunking to `1.0.2` is will cause it to encode the model in chunks but decode it in one string, which causes an invalid read of string, while the actual value itself is the number of chunks.
So perhaps a better way is to disable chunking in `1.0.x`? We can drop the backport to 1.0.x (better) or have 2 encoders (I prefer not).

**Comment by lantiga** [comment]
I see. I propose we could release proper chunking together with parallel DAG in a `1.1.0` release, while leaving chunking out for `1.0.x` (including the current backport.

**Comment by DvirDukhan** [comment]
Closing this PR

**Pull request closed without merging**
