### PR TITLE
Load default backend lazily if not set

### PR DESCRIPTION
**Pull request by lantiga**
Addresses #172 

This PR introduces a new CONFIG subcommand

```
AI.CONFIG BACKENDSPATH <path>
```

which also works as a command-line argument just like the other CONFIG subcommands.

BACKENDSPATH instructs RedisAI where to look for the default backends.

In addition, in case a path for a backend file is specified as a relative path, e.g.
```
AI.CONFIG LOADBACKEND TORCH redisai_torch/redisai_torch.so
```
the given path is interpreted as relative to the BACKENDSPATH.

In this case, if BACKENDSPATH is not specified, it will be assumed to be
```
<location_of_redisai.so>/backends
```

### CODE REVIEW

**Comment by K-Jo** [comment]
@lantiga is there a default BACKENDSPATH or will there be an exception if the command was not called or it was not set at module loadtime?

**Comment by lantiga** [comment]
It defaults to <where_redisai.so_is>/backends

**Comment by rafie** [comment]
Looks great. PS do we want to support env var REDISAI_BACKENDS_PATH?

**Comment by lantiga** [comment]
> Looks great. PS do we want to support env var REDISAI_BACKENDS_PATH?

Right now there's a `BACKENDSPATH` command-line argument, we can surely support the env var as well. Let's merge this, can you please follow-up regarding this point at #172?

**Pull request merged**
